version: '3.2'
services:
  web-app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: on-failure
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    restart: on-failure
    volumes:
      - data:/db/data
    environment:
      - POSTGRES_DB=rest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
volumes:
  data:
